###
# @see https://docs.docker.com/reference/cli/docker/compose
# @see https://docs.docker.com/reference/compose-file/build
#
# Uncomment services to your needs
###

########
# MAIN #
########

services:

    # MAIN SERVER #
    server:
        container_name: server
        build:
            context: .
            args:
                IMAGE: ${MAIN_SERVER_IMAGE:-ubuntu}
                RECIPES: |
                    local/main_recipes.local
        ports: 
            - 80:80
            - 443:443
            - 5173:5173
        volumes:
            - .:/var/www


# Include compose files
include:

##################
# LOCAL / CUSTOM #
##################

    - ./local/add_services.yml${ADD_SERVICES_EXT-.dist}

##########
# SERVER #
##########
    # - .recipes/docker/node.yml
    # - .recipes/docker/php.yml
    # - .recipes/docker/php-apache.yml
    # - .recipes/docker/ubuntu.yml

############
# DATABASE #
############
    # - .recipes/docker/mariadb.yml
    # - .recipes/docker/mysql.yml
    # - .recipes/docker/postgres.yml
    # - .recipes/docker/redis.yml

# DATABASE ADMIN #
    # - .recipes/docker/adminer-standalone.yml
    # - .recipes/docker/phpmyadmin.yml

############
# NETWORKS #
############

# networks:
#     project_network:
