###
# @see https://docs.docker.com/reference/cli/docker/compose
# @see https://docs.docker.com/reference/compose-file/build
#
# Uncomment services to your needs
###

########
# MAIN #
########

# services:

    # MAIN SERVER #

    # main_server:
    #     container_name: main_server
    #     build:
    #         context: .
    #         dockerfile: .docker/Dockerfile
    #         args:
    #             IMAGE: ${MAIN_SERVER_IMAGE:-ubuntu}
    #     volumes:
    #         - ./app:/var/www
    #     working_dir: /var/www
    #     ports: 
    #         - ${MAIN_SERVER_PORTS:-80:80}
    #     command: sleep infinity

include:

    - ./compose.override.yml.local

##########
# SERVER #
##########

    # - .docker/compose/node.yml
    # - .docker/compose/php-apache.yml
    # - .docker/compose/ubuntu.yml

############
# DATABASE #
############

    # - .docker/compose/adminer.yml
    # - .docker/compose/mariadb.yml
    # - .docker/compose/mongo.yml
    # - .docker/compose/mysql.yml
    # - .docker/compose/postgres.yml
    # - .docker/compose/redis.yml

############
# NETWORKS #
############

# networks:
#     project_network:
