###
# @see https://docs.docker.com/reference/cli/docker/compose
# @see https://docs.docker.com/reference/compose-file/build
#
# Uncomment services to your needs
###

########
# MAIN #
########

services:

    # MAIN SERVER #
    server:
        container_name: server
        build:
            context: .
            args:
                IMAGE: ${MAIN_SERVER_IMAGE:-ubuntu}
                INSTALL_RECIPES: |
                    .local/main_recipes.local
        command: sleep infinity
        ports: 
            - ${MAIN_SERVER_PORTS:-80:80}
        volumes:
            - .:/var/www


# Include compose files
include:

##################
# LOCAL / CUSTOM #
##################

    - ./.local/add_services.yml${ADD_SERVICES_EXT-.dist}

##########
# SERVER #
##########
    # - .docker/compose-services/node.yml
    # - .docker/compose-services/php.yml
    # - .docker/compose-services/php-apache.yml
    # - .docker/compose-services/ubuntu.yml

############
# DATABASE #
############
    # - .docker/compose-services/mariadb.yml
    # - .docker/compose-services/mysql.yml
    # - .docker/compose-services/postgres.yml
    # - .docker/compose-services/redis.yml

# DATABASE ADMIN #
    # - .docker/compose-services/adminer-standalone.yml
    # - .docker/compose-services/phpmyadmin.yml

############
# NETWORKS #
############

# networks:
#     project_network:
