#!/usr/bin/env bash

# HELP #
display_usage() {
    echo "\
Usage:
  run [command]
HELP
  help              h         show list of commands
DOCKER COMMAND
  build_container   build
  run_container     run
  build_and_run     bnr
  connect_container co
  stop_container    stop
  stop_and_remove   snr
INSTALLING COMMAND
  create-project    create    create Symfony project with Maker bundle
  db-install        db        install Doctrine and Symfony Form
  qa-install        qa        install Php linters
";
}

##############
### DOCKER ###
##############

build_container() {
	docker build -t php-apache-img .
}

run_container() {
	docker run -it -d -v .:/var/www -p 8123:80 --name phpapache php-apache-img
}
	
build_and_run() {
	bash build_container
	bash run_container
}

connect_container() {
	docker exec -it phpapache bash
}

stop_container() {
	docker container stop phpapache 
}

remove_container() {
	docker container remove phpapache
}

stop_and_remove() {
	bash stop_container
	bash remove_container
}

###############
### INSTALL ###
###############

# CREATE #
create_project() {
    # create
    symfony new __project
    mv __project/* . && mv __project/.* . && rm -r __project
    curl https://raw.githubusercontent.com/cylmat/symplay/refs/heads/main/public/.htaccess -o public/.htaccess

    # make
    composer req --dev maker
    chmod a+w -R .
    echo 'Test' | bin/console make:controller
    echo 'Access test page on "http://localhost:8123/test"'
}

# DATABASE #
db_install() {
    # doctrine
    composer req doctrine --no-interaction
    sed -ie 's/DATABASE_URL="postgresql/# DATABASE_URL="postgresql/' .env
    sed -ie 's/# DATABASE_URL="sqlite/DATABASE_URL="sqlite/' .env

    # form
    composer require form validator twig-bundle security-csrf
    echo 'Use "bin/console make:entity" or "bin/console make:crud"'
}

# QA #
qa_install() {
    mkdir -p tools
    composer req --dev --working-dir=tools friendsofphp/php-cs-fixer phpmd/phpmd phpunit/phpunit phpstan/phpstan

    echo "See: [https://phpqa.io] and [https://github.com/easy-coding-standard]
    Suggested: [https://github.com/jakzal/toolbox] and [https://github.com/EdgedesignCZ/phpqa]"
}

if [[ -z "$@" ]]; then
  display_usage
fi

for i in "$@"; do
    case $i in
        # docker
        build_container|build)
            build_container
        ;;
        run_container|run)
            run_container
        ;;
        build_and_run|bnr)
            build_container
            run_container
        ;;
        connect_container|co)
            connect_container
        ;;
        stop_container|stop)
            stop_container
        ;;
        remove_container|rm)
            remove_container
        ;;
        stop_and_remove|snr)
            stop_container
            remove_container
        ;;
        # install
        create_project|create)
            create_project
        ;;
        db_install|db)
            db_install
        ;;
        qa_install|qa)
            qa_install
        ;;
        help|h)
            display_usage
        ;;
    esac
done

exit 0
