
services:

    mysql:
        image: mysql
        restart: always
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: ${MYSQL_USER:-user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-pass}
            MYSQL_DATABASE: mydb
            MYSQL_TCP_PORT: ${MYSQL_TCP_PORT:-3306}
        ports: 
            - ${MYSQL_PORTS:-3306:3306}
        volumes:
            #- ../config/mysql/my.cnf:/etc/mysql/my.cnf:ro
            - ../fixtures/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
            - mysql-v:/var/lib/mysql
        ##########
        # IMPORT : mysql database < script.sql
        ##########

    phpmyadmin:
        image: phpmyadmin
        restart: always
        environment: 
            - PMA_ARBITRARY=1
        ports: 
            - ${PHPMYADMIN_PORTS:-8080:80}
        depends_on:
            - mysql

volumes:
    mysql-v: