#!/usr/bin/env bash

# https://medium.com/@jananis20011/mern-stack-full-project-setup-for-beginners-00a8a70ffe19





echo " > INSTALLING MERN BACKEND"

./bin/install express-app --port 3010



echo " > INSTALLING MERN FRONTEND"

./bin/install react-app --port 3011



### FRONTEND ###


############## package.json

# jq ". += {\"proxy\": \"http://localhost:$BACKEND_PORT\"}" package.json > \
#     /tmp/package.json && mv /tmp/package.json package.json

