#!/usr/bin/env bash

# https://api-platform.com

###
# NEED
###

# phpext.db (sql)
# composer
# maker bundle


###
# ENV
###
echo "Usage: $0 --project-dir <project_dir>";

PROJECT_DIR=api-platform

eval set -- $(getopt -o '' --long project-dir:,help:,desc: -- "$@")
while true; do case "$1" in
    --desc)        echo "desc"; shift;;
    --project-dir) echo "Api project directory created in $2"; PROJECT_DIR="$2"; shift 2;;
    --help)        echo "help"; shift;;
    --)            shift; break;;
esac; done
### -env


# RUN
symfony new $PROJECT_DIR
cd $PROJECT_DIR

### Use api-platform/api-pack & symfony/orm-pack
echo 'y' | symfony composer require api


# @todo better way to handle this
chmod 777 -R .

symfony console doctrine:database:create
symfony console doctrine:schema:create

### MODIFY DATABASE URL IN .ENV

### use composer require symfony/maker-bundle --dev
### use echo 'yes' | php bin/console make:migration
### use echo 'yes' | php bin/console doctrine:migrations:migrate
### use echo 'TestApi' | php bin/console make:entity --api-resource 
### echo "go to http://localhost:81/api/test_apis"

PORT=81
echo "Run: 'symfony serve --dir=. --listen-ip=0.0.0.0 --port=$PORT -d' to launch the api server."
