services:

    node:
        image: node
        container_name: node
        ports: 
            - ${NODE_PORTS:-3000-3009:3000-3009}
        command: sleep infinity
        user: ${UID}:${GID}
        working_dir: /var/www
        volumes: 
            - ../../app:/var/www
