services:

    php:
        build: 
            dockerfile: ./php.Dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        container_name: php
        command: sleep infinity
        ports: 
            - ${PHP_PORTS:-80:80}
        user: ${UID}:${GID}
        working_dir: /var/www
        volumes: 
            - ../../app:/var/www
