services:

    ubuntu:
        image: ubuntu
        container_name: ubuntu
        ports: 
            - ${UBUNTU_PORTS:-80:80}
        user: ${UID}:${GID}
        volumes: 
            - ../../app:/var/www
        working_dir: /var/www
        command: sleep infinity