#!/usr/bin/env bash

# doctrine
composer req doctrine --no-interaction

sed -ie 's/DATABASE_URL="postgresql/# DATABASE_URL="postgresql/' .env
sed -ie 's/# DATABASE_URL="sqlite/DATABASE_URL="sqlite/' .env

# easy admin
# https://symfony.com/bundles/EasyAdminBundle/current/dashboards.html
composer req easycorp/easyadmin-bundle

echo "Use: php bin/console make:admin:dashboard"

# form
composer require \
    form \
    validator \
    twig-bundle \
    security-csrf

echo 'Use "bin/console make:entity" or "bin/console make:crud"'
