#!/usr/bin/env bash



composer require --dev \
    friends-of-phpspec/phpspec-code-coverage \
    nikic/php-parser \
    phpro/grumphp \
    squizlabs/php_codesniffer



# ${PHP_DIR}/csfixer
# ${PHP_DIR}/phan
# ${PHP_DIR}/phpmd
# ${PHP_DIR}/phpstan
# ${PHP_DIR}/psalm
