#!/usr/bin/env bash



composer require --dev \
    brianium/paratest \
    behat/behat \
    pestphp/pest \
    phpspec/phpspec \
    phpunit/phpunit \
    phpunitgen/console \
    sebastian/phpcpd 
    
