#!/usr/bin/env bash


### SYMFONY CLI

echo "Installing Symfony cli...";

apt install -y curl

curl -sS https://get.symfony.com/cli/installer | bash
mv /root/.symfony5/bin/symfony /usr/local/bin/symfony
chmod a+x /usr/local/bin/symfony

# curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | bash
# apt install -y symfony-cli






### COMPOSER

echo "Installing Composer...";

which curl || apt install -y curl

curl -sS https://raw.githubusercontent.com/cylmat/docs/refs/heads/main/install/script/composer-install.sh | bash
mv ./composer.phar /usr/local/bin/composer
chmod a+x /usr/local/bin/composer

composer --version