#!/usr/bin/env bash

# https://api-platform.com
# https://api-platform.com/docs/symfony/#installing-the-framework

FG_YELLOW="\e[33m"
FG_CYAN="\e[36m"
NO_COLOR="\e[0m"

display_info_block

echo -e "$FG_YELLOW How to install Api-Platform project... $NO_COLOR";

# Use api-platform/api-pack & symfony/orm-pack

echo -e "
# 1. Check pdo_mysql or pdo_postgres is installed with $FG_CYAN  
bin/install php/ext/database $NO_COLOR

# 2. Run $FG_CYAN 
symfony new project-api
cd project-api $NO_COLOR

# 3. Run $FG_CYAN 
symfony composer require api --no-interaction $NO_COLOR $FG_YELLOW

 - doctrine/doctrine-bundle:
Modify your DATABASE_URL config in project's .env $NO_COLOR

# 4. Run $FG_CYAN
- api-platform/symfony:
Create API resource in src/ApiResource:
composer require symfony/maker-bundle --dev
php bin/console make:entity --api-resource $NO_COLOR

# 5. Run  $FG_CYAN
symfony console doctrine:database:create
symfony console doctrine:schema:create $NO_COLOR

Go to project parent directory: $FG_CYAN
cd .. $NO_COLOR
"

echo -e "$FG_YELLOW
Run to launch the api server: 
export PORT=80 
symfony serve --dir=project-api --listen-ip=0.0.0.0 --port=\${PORT} -d
Go to http://localhost:\${PORT}/api 

symfony server:log
symfony server:list
symfony server:stop --dir=project-api $NO_COLOR
"