#!/usr/bin/env bash

# https://api-tools.getlaminas.org

echo "Installing Laminas Api-Tools...";

composer create-project laminas-api-tools/api-tools-skeleton api-tools
cd api-tools

echo "Run:"
echo "php -S 0.0.0.0:8080 -t public public/index.php"
