#!/usr/bin/env bash

# https://api-tools.getlaminas.org


### NOT WORKING ###


# echo "Installing Laminas Api-Tools...";

# composer create-project laminas-api-tools/api-tools-skeleton laminas-api-tools
# cd api-tools

# echo "Run:"
# echo "php -S 0.0.0.0:8080 -t laminas-api-tools/public/index.php"
