#!/usr/bin/env bash

FG_YELLOW="\e[33m"
FG_CYAN="\e[36m"
NO_COLOR="\e[0m"

display_info_block
echo -e "$FG_YELLOW How to install Symfony project... $NO_COLOR";

# CREATE
echo "Run:"
echo -e "$FG_CYAN
symfony new symfony-app
cd symfony-app $NO_COLOR"

# echo "Use this in case of Apache Http server:"
# echo "curl https://raw.githubusercontent.com/cylmat/symplay/refs/heads/main/public/.htaccess -o symfony-app/public/.htaccess"

# MAKE
echo -e "$FG_CYAN
composer req --dev symfony/maker-bundle
echo 'Test' | bin/console make:controller
cd .. $NO_COLOR"

# INFO

echo -e "$FG_YELLOW Run :
export PORT=80
symfony local:server:start --dir=symfony-app --listen-ip=0.0.0.0 --port=\$PORT -d
Access test page on http://0.0.0.0:\$PORT/test $NO_COLOR"