#!/usr/bin/env bash


echo "-----------------------"
echo "Install Symfony project"
echo "-----------------------"


# CREATE
symfony new symfony-app

# echo "Use this in case of Apache Http server:"
# echo "curl https://raw.githubusercontent.com/cylmat/symplay/refs/heads/main/public/.htaccess -o symfony-app/public/.htaccess"



# INFO

# export PORT=80
# symfony local:server:start --dir=symfony-app --listen-ip=0.0.0.0 --port=\$PORT -d

# Access test page on http://0.0.0.0:\$PORT/test
