#!/usr/bin/env bash


PROJECT=symfony-app

for arg in "$@"; do
    if [[ $arg == --project-name=* ]]; then PROJECT="${arg#--project-name=}"; fi;
done


echo
echo "------------------"
echo "Create Symfony App"
echo "------------------"
echo


echo "Create Symfony project: $PROJECT"

# CREATE
symfony new "$PROJECT"

# echo "Use this in case of Apache Http server:"
# echo "curl https://raw.githubusercontent.com/cylmat/symplay/refs/heads/main/public/.htaccess -o symfony-app/public/.htaccess"


# INFO

# export PORT=80
# symfony local:server:start --dir=symfony-app --listen-ip=0.0.0.0 --port=\$PORT -d

# Access test page on http://0.0.0.0:\$PORT/test
