#!/usr/bin/env bash

# https://create-react-app.dev

npm create vite@latest react-app -- --template react

cd react-app
chmod 777 -R .
npm install


echo 'Run: "npm run dev"'

###
# or
#
# npx create-react-app react-app
# chmod 777 -R react-app