#!/usr/bin/env bash

# https://cs.symfony.com

mkdir --parents tools/php-cs-fixer
composer require --working-dir=tools/php-cs-fixer friendsofphp/php-cs-fixer

# curl -L https://cs.symfony.com/download/php-cs-fixer-v3.phar -o bin/php-cs-fixer
# chmod a+x bin/php-cs-fixer
