#!/usr/bin/env bash

# https://expressjs.com
# https://expressjs.com/fr/starter/installing.html

FG_RED="\e[31m"
FG_YELLOW="\e[33m"
FG_CYAN="\e[36m"
NO_COLOR="\e[0m"

display_info_block
echo -e "$FG_YELLOW How to create EXPRESS project $NO_COLOR"

echo -e "$FG_CYAN
npm install express --save -g
npm install express-generator -g
express express-app

cd express-app
npm install
$NO_COLOR"

echo -e "$FG_YELLOW  
export PORT=80 
DEBUG=express-project:* npm start $NO_COLOR"


################
### ONE FILE ###
################
# mkdir express
# cd express
# npm init
# echo '
# const express = require("express")
# const app = express()
# const port = 3000
# app.get("/", (req, res) => {
#   res.send("Hello World!")
# })
# app.listen(port, () => {
#   console.log(`Example app listening on port ${port}`)
# })
# ' > app-onefile.js
# echo "run: node app-onefile.js"

