#!/usr/bin/env bash

# https://expressjs.com
# https://expressjs.com/fr/starter/installing.html


npm install express --save -g
npm install express-generator -g

cd /var/www
express express-app

cd express-app
npm install

# DEBUG=express-project:* npm start


################
### ONE FILE ###
################

# mkdir express
# cd express
# npm init
# echo '
# const express = require("express")
# const app = express()
# const port = 3000
# app.get("/", (req, res) => {
#   res.send("Hello World!")
# })
# app.listen(port, () => {
#   console.log(`Example app listening on port ${port}`)
# })
# ' > app-onefile.js
# echo "run: node app-onefile.js"

