#!/usr/bin/env bash

# https://expressjs.com
# https://expressjs.com/fr/starter/installing.html
# https://expressjs.com/en/starter/generator.html



EXPRESS_APP=express-app
PORT=3001

for arg in "$@"; do
    if [[ $arg == --project-name=* ]]; then EXPRESS_APP="${arg#--project-name=}"; fi;
    if [[ $arg == --port=* ]]; then PORT="${arg#--port=}"; fi;
done



echo
echo "---------------"
echo "INSTALL EXPRESS"
echo "---------------"
echo



cd /var/www
mkdir $EXPRESS_APP
cd $EXPRESS_APP


npm init -y

npm install body-parser cors dotenv express mongoose --save
npm install nodemon --save-dev


###
# body-parser → Parses JSON data
# cors → Allows frontend to talk to backend
# dotenv → Loads environment variables
# express → Handles API requests
# mongoose → Connects to MongoDB
# nodemon → Restarts server automatically when files change
###


###
# from nodemon
#
# $ npx nodemon app.js
###


echo
echo "-------------------"
echo "Creating demo files"
echo "-------------------"
echo



############## .env

cat <<EOF > .env
MONGO_URI=mongodb://root:root@mongo:27017/expressDB?authSource=admin
PORT=$PORT
EOF


############## package.json

curl -s https://webinstall.dev/jq | bash
source ~/.config/envman/PATH.env

jq ".scripts += {\"start\": \"node app.js\", \"dev\": \"nodemon app.js\", \"kill\": \"pkill -f 'express-app|nodemon|node app.js'\"}" package.json > \
    /tmp/package.json && mv /tmp/package.json package.json

# Use it with ES Module "import"
jq '.type = "module"' package.json > /tmp/package.json && mv /tmp/package.json package.json


############## app.js

cat <<EOF > app.js
import cors from "cors";
import dotenv from "dotenv";
import express from "express";
import mongoose from "mongoose";
import userRoute from "./routes/user.js";

dotenv.config();
const app = express();
const PORT = process.env.PORT || $PORT;

// Middleware
app.use(cors());
app.use(express.json()); // need to POST -H "Content-Type: application/json"

// MongoDB Connection
mongoose
  .connect(process.env.MONGO_URI, { useNewUrlParser: true, useUnifiedTopology: true })
  .then(() => console.log("MongoDB Connected"))
  .catch((err) => console.log(err));

// Routes
app.get("/", (req, res) => {
  res.send("API Express is running...");
});
app.use("/api/user", userRoute);

// Listen
app.listen(PORT, () => console.log(\`Server running on port ${PORT}\`));
EOF


############## routes/user.js

if [ ! -d routes ]; then mkdir routes; fi

cat <<EOF > routes/user.js
import express from "express";
import User from "../models/User.js";

const router = express.Router();

// Get users 
// curl -X GET http://localhost:$PORT/api/user

// Create user
// curl -X POST http://localhost:$PORT/api/user -d '{"name":"John Doe","email":"jdoe@me.com","phone":"012345678"}'

// Register User
router.post("/", async (req, res) => {
  const { name, email, phone } = req.body;
  try {
    const newUser = new User({ name, email, phone });
    await newUser.save();
    res.status(201).json(newUser);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Get All Users
router.get("/", async (req, res) => {
  const users = await User.find();
  res.json(users);
});

export default router;
EOF


############## models/User.js

if [ ! -d models ]; then mkdir models; fi

cat <<EOF > models/User.js
import mongoose from "mongoose";

const userSchema = mongoose.Schema({
  name: String,
  email: String,
  phone: String
}, { timestamps: true });

export default mongoose.model("User", userSchema);
EOF


############## sample.js

cat <<EOF > sample.js
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.listen(port, () => {
  console.log(\`Example app listening on port ${port}\`)
})
EOF



##########

echo
echo "Express App installed [OK]"


