#!/usr/bin/env bash

# https://yeoman.io
# https://yeoman.io/generators/


echo "npm install -g yo"
echo "npm install -g generator-webapp"

echo "# Create project"
echo "yo webapp"
echo "# yo webapp --help"

echo "# Access home"
echo "npm home generator-webapp"

# sample
# yo --generators
# yo doctor
# yo angular:controller MyNewController
