#!/usr/bin/env bash

# https://create-react-app.dev

npm create vite@latest react-app -- --template react

cd react-app
npm install


echo 'Run: "npm run dev"'

###
# or
#
# npx create-react-app react-app