#!/usr/bin/env bash

# https://create-react-app.dev

# FG_RED="\e[31m"
# FG_YELLOW="\e[33m"
# FG_CYAN="\e[36m"
# NO_COLOR="\e[0m"

# display_info_block
# echo -e "$FG_YELLOW How to create REACT project $NO_COLOR"

# echo -e "$FG_CYAN 
npm create vite@latest react-app -- --template react $NO_COLOR"

# or
# npx create-react-app react-app

# echo -e "$FG_CYAN
cd react-app
npm install $NO_COLOR"


echo -e "$FG_YELLOW
export PORT=80 $FG_RED
# on npm 7+, extra double-dash -- is needed $FG_YELLOW
npm run dev -- --host 0.0.0.0 --port \$PORT $NO_COLOR
cd .."
