#!/usr/bin/env bash

# https://github.com/nvm-sh/nvm
# As nvm is a sourced function(), not a shell script, it can be used anywhere without alias
# Then run "nvm install node"

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
source "$HOME/.nvm/nvm.sh" && source "$HOME/.nvm/bash_completion"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

nvm --version
