#!/usr/bin/env bash

echo "Installing Symfony project...";

###
# ENV
###
echo "Usage: $0 --project-dir <project_dir>";

PROJECT_DIR=symfony_project

eval set -- $(getopt -o '' --long project-dir:,help:,desc: -- "$@")
while true; do case "$1" in
    --desc)        echo "desc"; shift;;
    --project-dir) echo "Symfony project directory created in $2"; PROJECT_DIR="$2"; shift 2;;
    --help)        echo "help"; shift;;
    --)            shift; break;;
esac; done
### -env

# DEPENDENCIES
which composer || ./bin/install php/composer
which symfony  || ./bin/install php/symfony-cli

# CREATE
symfony new ${PROJECT_DIR}

# Use this in case of Apache Http server
# curl https://raw.githubusercontent.com/cylmat/symplay/refs/heads/main/public/.htaccess -o ${PROJECT_DIR}/public/.htaccess

# MAKE
# composer req --dev symfony/maker-bundle
# chmod a+w -R .
# echo 'Test' | bin/console make:controller
# echo 'Access test page on "http://localhost:80/test"'

# # INFO
LISTEN_IP=0.0.0.0
echo "Run 'symfony local:server:start --dir=${PROJECT_DIR} --listen-ip=$LISTEN_IP' -d"
