#!/usr/bin/env bash

# https://qossmic.github.io/deptrac

apt update && apt-get install -y graphviz
curl -L https://github.com/qossmic/deptrac/releases/download/1.0.0/deptrac.phar -o bin/deptrac
chmod a+x bin/deptrac
