#!/usr/bin/env bash

# https://symfony.com/download

###
# ENV
###
echo "Usage: $0";

eval set -- $(getopt -o '' --long help:,desc: -- "$@")
while true; do case "$1" in
    --desc)        echo "desc"; shift;;
    --help)        echo "help"; shift;;
    --)            shift; break;;
esac; done
### -env

curl -sS https://get.symfony.com/cli/installer | bash
mv /root/.symfony5/bin/symfony /usr/local/bin/symfony
chmod a+x /usr/local/bin/symfony

# curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | bash
# apt install -y symfony-cli
