#!/usr/bin/env bash



PROJECT="symfony-app"

for arg in "$@"; do
    if [[ $arg == --container-name=* ]]; then CONTAINER="${arg#--container-name=}"; fi; 
    if [[ $arg == --project-name=* ]]; then PROJECT="${arg#--project-name=}"; fi;
done


echo
echo "---------------------"
echo "Install Symfony stack"
echo "---------------------"
echo



./bin/install git $CONTAINER
./bin/install composer $CONTAINER
./bin/install symfony-cli $CONTAINER

./bin/install apache-config $CONTAINER --project-name=$PROJECT
./bin/install symfony-app $CONTAINER --project-name=$PROJECT
