#!/usr/bin/env bash

INSTALL_BIN=".recipes/install"

${INSTALL_BIN} csfixer
${INSTALL_BIN} codeception
${INSTALL_BIN} infection
${INSTALL_BIN} parallel
${INSTALL_BIN} phan
${INSTALL_BIN} phpmd
${INSTALL_BIN} phpstan
${INSTALL_BIN} psalm
