#!/usr/bin/env bash

SYSTEM_APT_COMMON_INSTALL=${SYSTEM_APT_COMMON_INSTALL:=zip}

apt update

apt install -y \
    bzip2 \
    jq \
    vim \
    zip

if [ ! -z "$SYSTEM_APT_COMMON_INSTALL" ]; then
    apt install -y {$SYSTEM_APT_COMMON_INSTALL}
fi
