#!/usr/bin/env bash

# https://git-scm.com

apt-get install -y git

git init

git config --local user.email 'you@example.com'
git config --local user.name 'Your Name'
git config --local user.email 'you@example.com'
git config --local user.name 'Your Name'