#!/usr/bin/env bash


FG_BLACK=30
FG_CYAN=36
BG_CYAN=46
NO_COLOR="\e[0m"

echo -e "\e[${BG_CYAN};${FG_CYAN}m              ${NO_COLOR}"
echo -e "\e[${BG_CYAN};${FG_BLACK}m Informations ${NO_COLOR}"
echo -e "\e[${BG_CYAN};${FG_CYAN}m              ${NO_COLOR}"
