
services:

    mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            # MYSQL_USER: root
            # MYSQL_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_TCP_PORT: 3306
        ports: [3306:3306]
        volumes:
            #- ../config/mysql/my.cnf:/etc/mysql/my.cnf:ro
            - ../fixtures/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
            - mysql:/var/lib/mysql
        ##########
        # IMPORT : mysql database < script.sql
        ##########

volumes:
    mysql: