services:

    node:
        image: node
        container_name: node
        ports: 
            - ${NODE_PORTS:-3000:3000}
        volumes: 
            - ../../app:/var/www
        working_dir: /var/www
        command: sleep infinity
