#!/usr/bin/env bash

# https://infection.github.io

apt update && apt install -y gpg
curl -L https://github.com/infection/infection/releases/download/0.26.6/infection.phar -o bin/infection
curl -L https://github.com/infection/infection/releases/download/0.26.6/infection.phar.asc -o /tmp/infection.phar.asc
gpg --recv-keys C6D76C329EBADE2FB9C458CFC5095986493B4AA0
gpg --with-fingerprint --verify /tmp/infection.phar.asc bin/infection
rm /tmp/infection.phar.asc
chmod +x bin/infection
