#!/usr/bin/env bash

# https://symfony.com/download


echo "----------------------"
echo "Installing Symfony-cli"
echo "----------------------"



curl -sS https://get.symfony.com/cli/installer | bash
mv $HOME/.symfony5/bin/symfony /usr/local/bin/symfony
chmod a+x /usr/local/bin/symfony

symfony -V

# curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | bash
# apt install -y symfony-cli
